# Write your MySQL query statement below
SELECT 
    ROUND(
        COUNT(DISTINCT PLAYER_ID) / 
        (SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY), 2
    ) AS FRACTION
FROM ACTIVITY A
WHERE (PLAYER_ID, EVENT_DATE) IN (
    SELECT PLAYER_ID, DATE_ADD(MIN(EVENT_DATE), INTERVAL 1 DAY) AS NEXT_LOGIN_DAY
    FROM ACTIVITY
    GROUP BY PLAYER_ID
);