# Write your MySQL query statement below
SELECT T.CONSECUTIVENUMS FROM
(SELECT A.NUM AS CONSECUTIVENUMS 
FROM LOGS A JOIN LOGS B  
ON A.NUM=B.NUM AND B.ID-A.ID=1
JOIN LOGS C
ON A.NUM=C.NUM
AND C.ID-B.ID=1) AS T
GROUP BY CONSECUTIVENUMS;
